FROM public.ecr.aws/lambda/python:3.12

# Lambda 전용 의존성
COPY requirements-lambda.txt .
RUN pip install -r requirements-lambda.txt

# 소스 코드 복사
COPY src/infrapilot/ ${LAMBDA_TASK_ROOT}/infrapilot/

# Lambda 핸들러 지정
CMD ["infrapilot.lambda_.handler.handler"]