apiVersion: apps/v1
kind: Deployment
Metadata:
  name: infrapilot-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infrapilot-web
  template:
    metadata:
      labels:
        app: infrapilot-web
    spec:
      containers:
      - name: web
        image: 773320320276.dkr.ecr.ap-northeast-2.amazonaws.com/infrapilot-web:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"
        resources:
          requests:
            memory: "150Mi"
          limits:
            memory: "250Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: infrapilot-web
spec:
  selector:
    app:  infrapilot-web
  ports:
  - port:  8000
    targetPort:  8000